<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'glyphicons halflings' => array(
    'normal' => $fontDir . '/glyphicons-halflings-normal_697c7351916c68acf96b964b74fbde94',
  ),
  'fontawesome' => array(
    'normal' => $fontDir . '/fontawesome-normal_ad1a8d9b014e3e063171413bce94f8e6',
  ),
  'bucket-ico-font' => array(
    'normal' => $fontDir . '/bucket-ico-font-normal_8e3c72cce00e761e6f228b084b866c77',
  ),
  'material-design-iconic-font' => array(
    'normal' => $fontDir . '/material-design-iconic-font-normal_b8bca5ea5bba58eb6a2937d393045e7a',
  ),
  'roboto' => array(
    '100_italic' => $fontDir . '/roboto-100-italic_57b4f9f22b6b458397f660428af4302d',
    '300_italic' => $fontDir . '/roboto-300-italic_f4ae12bda54fc9ba5f9e48b689578908',
    'italic' => $fontDir . '/roboto-italic_8195011e157d3a377682d918ecaef444',
    '500_italic' => $fontDir . '/roboto-500-italic_6d3b05813203ec80ec7c8ee056da57a6',
    'bold_italic' => $fontDir . '/roboto-bold-italic_ae95383317fc48c6f5e0c45b4aba2ce8',
    '900_italic' => $fontDir . '/roboto-900-italic_b7194243f0f506ddb72c4386b49363c7',
    '100' => $fontDir . '/roboto-100_4f648b1e497c5aed1e7e0e5a635dc480',
    '300' => $fontDir . '/roboto-300_fe6b835b8e32bf4538141610f4e4d56f',
    'normal' => $fontDir . '/roboto-normal_cf99a9d56c411ce3fa8a2fc49c520e74',
    '500' => $fontDir . '/roboto-500_3fd317e52bc3050f32e57a7e30e4f32c',
    'bold' => $fontDir . '/roboto-bold_1e996688829091a02d8ce32f4ce56696',
    '900' => $fontDir . '/roboto-900_659255be657c177506520d1187c03c76',
  ),
) ?>